### PR TITLE
Add Slack notifications when deploys from CI fail

### PR DESCRIPTION
**Pull request by 46bit**
What
----

Get Slack notifications when things deployed by our build CI fail to deploy.

Recently runs 186, 188, 189, 190, 191, 194, 196, 197, 198, 199, 201, 204 and 205 of the `paas-tech-docs` release pipeline failed, delaying some changes from going live by as much as two weeks!

See commit message for many more details.

How to review
-------------

* Code review;
* Review alongside https://github.com/alphagov/paas-credentials/pull/148

Who can review
--------------

Not @46bit

### CODE REVIEW

**Comment by 46bit** [comment]
I'm talking to IT about getting a webhook added for this. Leaving this as a draft PR until the "other half" of it is ready.

**Comment by richardTowers** [comment]
Do you mean "review alongside https://github.com/alphagov/paas-credentials/pull/148" ? Your link put me in circles ♻️ 💫

**Comment by 46bit** [comment]
@richardTowers I do, oops!

**Comment by richardTowers** [comment]
:shipit: - I've merged the other PR - looks good to me

**Pull request merged**
